export const privacyPolicyParagraphs = [
  "Last Modified:",
  ["Overview", "2"],
  ["Applicability of HIPAA and GLBA", "2"],
  ["Information Collected for Texting Program", "2"],
  ["Personal Information We Collect / Sources of Personal Information", "2"],
  ["Use of Personal Information", "2"],
  "Disclosing Personal Information",
  ["Cookie Policy", "3"],
  ["Children Under the Age of 16", "2"],
  ["Your Privacy Rights", "7"],
  "Your Privacy Rights – California",
  ["Retention of Data", "2"],
  ["Data Security", "2"],
  ["Third-Party Applications and Integrations", "2"],
  ["Updates to This Privacy Policy", "2"],
  ["Contact Information", "3"],
  "The purpose of the Platform is to provide information and tools to licensed insurance agents and prospective insurance agents (“Agents”). We also receive information about individuals who are interested in insurance or financial products (“Consumers”) and make such information available to licensed insurance agents who assist individuals with the purchase of the products (“Services”). We may also work with “Lead Vendors” – companies that collect inquiries from Consumers and pass such inquiries to Agents and Company representatives. Lead Vendors must obtain appropriate consent from Consumers to be contacted regarding specific products before providing us with such Consumers’ information.",
  "This Privacy Policy uses the term “Personal Information” to describe information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household.",
  "Since we facilitate the sale of a diverse range of insurance products, our processing of some information on behalf of our agents may fall under another state or federal regulatory framework, like the Health Insurance Portability and Accountability Act (“HIPAA”) and related state laws, or the Gramm-Leach-Bliley Act (“GLBA”) and related state laws.",
  "Specifically, we act as a Business Associate (as defined by HIPAA) if we receive client Protected Health Information (“PHI”) from lead vendors or on behalf of a health plan that is a Covered Entity (as defined by HIPAA). In our role as a Business Associate we collect, use, and disclose PHI to provide services for or on behalf of health plans. For more information about how PHI is used and disclosed, please review the applicable health plan’s Notice of Privacy Practices.",
  "When we receive client information pertaining to certain insurance or financial products, we may collect non-public personal financial information, which is regulated by GLBA. For more information about how non-public personal financial information is used and disclosed, please review the GLBA Notice provided by the financial institution that issued the clients’ policies or products.",
  "This Privacy Policy applies to personal information that is not covered by HIPAA or GLBA.",
  "Any information that we collect when you opt into receiving SMS and MMS text messages from us is used solely for the management of such texting communications program.  We do not transfer your consent to be contacted via the texting program to any other entity.",
  "The table below details the categories of Personal Information that we may collect or obtain through the operation of the Platform. In addition to the sources listed below, we may collect this information from third-party service providers or vendors, including data analytics providers.",
  "Consumers’ and Agents’ name, phone number, and email address, as well as Consumers’ postal address.",
  "We may collect this information about Consumers from Lead Vendors, Agents, insurance carriers, data brokers, and agencies.",
  "We collect this information about Agents from Agents or marketing organizations in the Agents’ product sale hierarchy.",
  "This includes username and password* when Agents or Consumers choose to create an account with us.",
  "Agents’ National Producer Number and Social Security number.",
  "We collect this information from Agents when they begin working with us.",
  "Consumers’ driver’s license, Social Security, and/or similar government-issued identification numbers.",
  "We collect this information about Consumers provided in the course of discussions with an Agent or representative, which is relevant to the processing of an application for an insurance or financial product.",
  "Consumers’ age, date of birth, marital status, language preference, ethnicity, race, and sex or gender.",
  "We collect this information about Consumers when Lead Vendors, insurance carriers, Agents, data brokers, or agencies provide it to us.",
  "Consumers’ health information provided in the course of discussions with an Agent or representative, which is relevant to the processing of an application for an insurance or financial product. For example, notes about a Consumer may state that the Consumer has diabetes, as is relevant for an application for a life insurance product.",
  "Audio recordings of Consumer conversations with representatives and Agents in connection with inquiries regarding insurance and/or financial products. We may also have access to video snippets of user website activity evidencing consent to be contacted. This information is collected from Lead Vendors, Agents, insurance carriers, and agencies.",
  "We collect information about the products requested by Consumers, including information entered into insurance and/or financial product applications, as provided by you, a Lead Vendor, Agent, data brokers, insurance carriers, advertising and/or social media networks, or an agency. We also collect information regarding your purchase of insurance and/or financial products, including the type of product purchased and the corresponding carrier.",
  "Automatically collected information on users’ interaction with the Platform. This may include your browsing history (including the site you came from before visiting our website and the site you went to after leaving our website), duration of browsing session, device ID, and IP address. We may also collect this information from advertising networks.",
  "We collect geolocation, which may include precise geolocation,* from users. We automatically collect this information from you and may also collect this from advertising networks.",
  "We collect from data brokers Personal Information about Consumers’ educational background, profession, income, product preference, consumer behavior, and asset ownership. This information is used for offline marketing. We also collect this information from Agents when they begin working with us.",
  "Some or all of the types of Personal Information marked with an asterisk (*) may be considered “sensitive” personal information according to some state laws.",
  "We may also partner with financial processors or payment vendors to provide services to Agents on the Platform.",
  "We do not collect biometric information relating to an individual’s physiological, biological, or behavioral characteristics including an individual’s DNA that can be used with other data to establish an individual’s identity.",
  "Your information may be provided to us by your spouse or other family member.",
  "We may use or disclose the Personal Information that we collect for one or more of the following purposes:",
  "Operate the Platform",
  "Communicate with you regarding the Platform",
  "Contact Consumers through our employed agents regarding insurance and/or financial products in which the Consumer expressed interest",
  "Address users’ and Consumers’ inquiries",
  "Process transactions",
  "Tailor the content and information that we may send or display to you",
  "Analyze use of our products and services",
  "Develop new products and services",
  "Comply with legal obligations",
  "Protect our rights, property, and safety or the rights, property, and safety of others; and",
  "Evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by us about our customers is among the assets transferred. You hereby consent to such transfers and we may assign and transfer all of the rights, benefits, duties, and obligations of this Privacy Policy, under the circumstances described in this paragraph.",
  "From time to time, we may contact users via email and mail, for the purpose of providing announcements, promotional offers, alerts, confirmations, surveys, and/or other general communication. If you would like to stop receiving marketing or promotional communications via email or mail from us, you may opt out of such communications by contacting us through the TrustArc portal, the toll-free number, or the email address listed below.",
  "We may also contact Agents, Consumers, and other users via text messaging, but only if such individuals opt in to receive text messages and only within the scope of such consent.",
  "With Our Service Providers. We may share Personal Information about Consumers and Agents with third parties who perform services for us or on our behalf. For example, this may include payment processors and companies that send emails on our behalf or other operating systems or platforms that help us run our services.",
  "With Our Business Partners. This includes our affiliates in the insurance or financial industry, insurance carriers, and any other entities that are involved in the sale of insurance or financial products such as marketing organizations that specialize in the insurance or financial industry.",
  "With Law Enforcement, Government Agencies, or Parties to a Legal Proceeding.",
  "We may share Personal Information with such entities to comply with the law or assist in law enforcement.",
  "With Our Independent Agents and Advisors.",
  "Agents and advisors have access to the Personal Information about Consumers that is provided by the Consumers when requesting information regarding insurance and/or financial products.",
  "With Data Analytics Providers and Advertising Service Providers.",
  "Third-party data analytics providers may collect Personal Information about users over time and across different websites, applications, and devices for the purposes of targeted advertising. These providers may collect Personal Information, specifically internet or other similar network activity information, your input on the website, social media information, and/or commercial information in this manner on our Platform. For more information on these third parties, please see the below “Cookie Policy.”",
  "We may partner with these third parties to tailor and customize our advertising to Users. The practice of targeted advertising may be considered a “sale” of Personal Information under some state laws. For more information about your choices related to this practice, please see “Your Privacy Rights” below.",
  "The website on which the Platform is hosted may use cookies, pixel tags, web beacons, and similar technologies to track and enhance user experience, including technologies placed on the website by third parties, such as advertising network partners. Users’ web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. Cookies can also enable us to track and target the interests of our users to enhance their experience on our website. We may use the following types of cookies: advertising and analytics and social media.",
  "You may choose to set your web browser to refuse cookies or to alert you when cookies are being sent. If you do so, some parts of the Platform may not function properly. Our Platform does not recognize “Do Not Track” signals, but it may recognize other opt-out preference signals, such as the Global Privacy Control (GPC). You may set such a signal through your browser or browser extension.",
  "The Platform is not intended for children under 16 years of age. We do not collect information about individuals under the age of 16. No one under age 16 may provide any information through the Platform. We do not knowingly collect Personal Information from children under 16, and we do not have actual knowledge that we sell or share the Personal Information of children under 16. If you are under 16, do not use or provide any information through the Platform. If we learn we have collected or received Personal Information from a child under 16 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 16, please contact us.",
  "State consumer privacy laws may provide their residents with additional rights regarding our use of their Personal Information as described in more detail below. However, these rights are not absolute, and, in certain cases, we may decline your request as permitted by law.",
  "You may request the categories of Personal Information collected by Company about the data subject, the purpose and source of that collection, whether or not the Personal Information was sold to a third party, and the categories of third parties to whom Company disclosed the data subject’s Personal Information.",
  "You may request to access, inspect, and receive a copy of Personal Information",
  "You may request to delete non-exempt Personal Information held or stored by Company or on Company’s behalf. Some exceptions apply to these types of requests.",
  [
    "You may request to edit or correct your Personal Information at any time.",
    "2",
  ],
  "You may request to opt-out of certain uses or disclosures of Personal Information, including selling or “sharing” (i.e., using Personal Information from non-Integrity websites for targeted advertising (“targeted advertising”)).",
  "Some data subjects may have the right to request that Company reconsider a denial of a data subject request.",
  "To appeal a decision regarding a consumer rights request, please fill out this form and include “APPEAL” in your request details, along with a short description of your prior request and the outcome that you are seeking. We may request more information in order to locate your prior request",
  "You may request the right to limit our use and disclosure of your Personal Information defined as sensitive under the CCPA.",
  "You have the right to be free from discrimination related to your exercise of any of your privacy rights.",
  "To exercise any of these rights, please click here. Only you, or under some state privacy laws, someone legally authorized to act on your behalf, may make a request related to your Personal Information.",
  "In order to protect your Personal Information from unauthorized access or deletion, we may require you to verify your account credentials before you can submit a data rights request.",
  [
    "Company is legally obligated to verify your identity when you submit a request. We may request additional information from you to verify your identity. If you submit a request to delete your Personal Information, you will also be required to confirm the deletion request by email.",
    "2",
  ],
  "If we are subsequently unable to confirm your identity, we may refuse your request.",
  "You may use an authorized agent to submit a data rights request. If you do so, the authorized agent must present signed written authorization to act on your behalf, and you will also be required to independently verify your own identity directly with us and confirm with us that you provided the authorized agent permission to submit the data rights request.",
  "To the extent the law applies to Company, Company is required under the California Consumer Privacy Act (“CCPA”), as amended, to provide certain information to California residents about how we collect, use, and share their Personal Information in our capacity as a business, and about the rights and choices California residents may have concerning their Personal Information. For purposes of this section, “Personal Information” has the meaning provided in the CCPA.",
  "This section applies only to California residents. As a California resident, you have the rights listed below. However, these rights are not absolute, and, in certain cases, we may decline your request as permitted by law. To exercise any of these rights, please click here. Only you, or someone legally authorized to act on your behalf, may make a request related to your Personal Information.",
  "The following disclosures are made in compliance with the CCPA, as amended. In the past twelve (12) months, we have collected the Personal Information described above, and disclosed it to the third parties listed under the section “Sharing Personal Information” for the business purposes identified therein and under the section “Use of Personal Information.” This information falls into the following categories of Personal Information under the CCPA:",
  "As disclosed above in “Sale and Sharing of Personal Information” we may engage in activity that may be considered “selling” or “sharing” Personal Information. If you wish to opt out of this use of your Personal Information, click here: Do Not Sell or Share My Personal Information",
  "We do not use or disclose sensitive Personal Information (indicated in the section “Personal Information We Collect” with an asterisk (*)) for purposes other than those specified in Cal. Code Regs. tit. 11, § 7027(m).",
  "Below is a summary of your rights under the CCPA. Please note that these rights are not absolute, and, in certain cases, we may decline your request as permitted by law",
  "You may request that we provide the following information about how we have collected and used your Personal Information:",
  "The categories of Personal Information we have collected about you;",
  "The sources from which that Personal Information was collected;",
  "The business or commercial purpose for collecting, selling, and/or sharing your Personal Information;",
  "The categories of Personal Information we shared or sold about you;",
  "The categories of third parties to whom we shared or sold Personal Information about you;",
  "The categories of Personal Information we disclosed for a business purpose; and",
  "The categories of third parties to whom we disclosed Personal Information about you for a business purpose.",
  "You may request a copy of your Personal Information.",
  "You may submit a request that Company disclose the categories and specific pieces of Personal Information that we have collected, used, or disclosed about you.",
  "Please note that simply because Company has provided the categories of Personal Information it may collect pursuant to California law does not mean Company necessarily collected all of the specific pieces of Personal Information listed for any given person. Also, please note where Personal Information was disclosed within the past twelve (12) months, it may have been disclosed only to service providers.",
  "You may have the right, under certain circumstances, to request that we delete the Personal Information you have provided to us.",
  "The CCPA may classify our use of some services as “selling” or “sharing” your Personal Information with the partners that provide the services. You can opt out of the “selling” and/or “sharing” of your Personal Information.",
  "We use sensitive Personal Information only as necessary for our (1) service delivery and operations, (2) compliance and protection, (3) quality control and improvements, or (4) Service improvement and analytics purposes in accordance with CCPA. If we use sensitive Personal Information outside the permitted purposes of CCPA, you have the right to limit such processing of sensitive Personal Information.",
  "In order to protect your Personal Information from unauthorized access or deletion, we may require you to verify your account credentials before you can submit a rights request. If you do not have an account with us, or if we suspect your account has been accessed without your authorization, we may ask you to provide additional Personal Information for verification.",
  "If we are subsequently unable to confirm your identity, we may refuse your rights request.",
  "You may use an authorized agent to submit a rights request. If you do so, the authorized agent must present signed written authorization to act on your behalf, and you will also be required to independently verify your own identity directly with us and confirm with us that you provided the authorized agent permission to submit the rights request. This verification process is not necessary if your authorized agent provides documentation showing that the authorized agent has power of attorney to act on your behalf under Cal. Prob. Code §§ 4121 to 4130.",
  "We facilitate the sale of insurance and financial products, and may engage in targeted advertising, which may be considered “selling” or “sharing” personal information as defined under certain state privacy laws, including California. In the last twelve (12) months, we have “sold” or “shared” the categories of personal information identified in “PERSONAL INFORMATION WE COLLECT” with advertising networks, data analytics vendors, insurance carriers, and Agents.",
  "NOTICE: We may sell your sensitive personal data.",
  "We retain Personal Information where we have an ongoing legitimate business or legal need to do so. Our retention periods will vary depending on the type of data involved, but, generally, we refer to these criteria in order to determine retention period:",
  "Whether we have a legal or contractual need to retain the data;",
  "Whether the data is necessary to provide our Platform; and",
  "Whether our Consumers or Agents would reasonably expect that we would retain the data until they remove it or until their accounts are closed or terminated.",
  "When we have no ongoing legitimate business need to process your Personal Information, we will either delete or anonymize it or, if this is not possible (for example, because your Personal Information has been stored in backup archives), then we will securely store your Personal Information and cease any further processing until deletion is possible.",
  "No security is foolproof, and the Internet is an insecure medium. We cannot guarantee absolute security, but we work hard to protect our Company and you from unauthorized access to or unauthorized alteration, disclosure, or destruction of Personal Information that we collect and store.",
  "Our Platform uses third-party applications and integrations to enhance its experience. We disclaim any and all liability and responsibility for the use of these applications and integrations, and encourage you to review their individual privacy policies before using our Platform or otherwise engaging with us. We disclaim any and all liability and responsibility for the use of these applications and integrations and encourage you to review any individual privacy policy related to those applications and integrations.",
  "We may revise this Privacy Policy from time to time. If we make material changes to this Privacy Policy, we will notify you by email or by posting a notice on our Platform prior to or on the effective date of the changes. By continuing to access or use the Platform after those changes become effective, you acknowledge the revised Privacy Policy.",
  "If you have any questions or comments about this notice, or the ways in which we collect and use your personal information, please do not hesitate to contact us at:",
];

export const consumerHealthParagraphs = [
  "This notice supplements the Privacy Notice and applies only to “consumer health data” subject to the Washington State My Health My Data Act (MHMDA).",
  "This notice describes the collection, use, and disclosure practices with respect to",
  "and any other websites or platforms that the Company may create in the future (the “Platform”)",
  "Individuals that are residents of Washington or individuals with consumer health data that has been collected in Washington should review this notice.",
  "The table below details the categories of Consumer Health Data that we may collect or obtain through the operation of the Platform and services we provide. In addition to the sources listed below, we may collect this information from third-party service providers or vendors. We may also infer certain information about you based on information provided from any of the sources listed below.",
  "Consumer’s health information provided in the course of discussions with an Agent or representative, which is relevant to the processing of an application for an insurance product. For example, notes about a Consumer may state that the Consumer has diabetes, as is relevant for an application for a life insurance product. ",
  [
    "Consumer’s health information provided in the course of discussions with an Agent or representative, which is relevant to the processing of an application for an insurance product.",
    "5",
  ],
  "Audio recordings of Consumer conversations with representatives and Agents in connection with inquiries regarding insurance products. We may also have access to video snippets of user website activity evidencing consent to be contacted. This information is collected from Lead Vendors, Agents, insurance carriers, and agencies.",
  "We may use or disclose the consumer health data that we collect for one or more of the following purposes:",
  "Provide our products and services;",
  "Operate the Platform",
  "Communicate with you regarding the Platform;",
  "Contact Consumers through our employed agents regarding insurance products in which the Consumer expressed interest;",
  "Address users’ and Consumers’ inquiries;",
  "Process transactions;",
  "Tailor the content and information that we may send or display to you;",
  "Analyze use of our products and services;",
  "Develop new products and services;",
  "Comply with legal obligations;",
  "Protect our rights, property, and safety or the rights, property, and safety of others; and",
  "Evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by us about our customers is among the assets transferred. You hereby consent to such transfers and we may assign and transfer all of the rights, benefits, duties, and obligations of this Privacy Notice, under the circumstances described in this paragraph.",
  "We may collect, use, or disclose of consumer health data to prevent, detect, protect against, or respond to security incidents, identity theft, fraud, harassment, malicious or deceptive activities, or any activity that is illegal under Washington state law or federal law; preserve the integrity or security of systems; or investigate, report, or prosecute those responsible for any such action that is illegal under Washington state law or federal law.",
  "We may disclose all categories of consumer health described above in “Consumer Health Data We Collect” to the third parties listed below for the purpose of facilitating the sale of insurance products to individuals who are interested in purchasing such products. We share consumer health data with:",
  "With Consumer concerning the health data;",
  "With our clients (i.e. insurance carriers so that they can provide coverage options based on the information the consumer provides);",
  "With data analytics providers;",
  "With service providers that help us provide our services and operate our business; and",
  "With our affiliates.",
  "As a Washington resident, or an individual with consumer health data collected in Washington, you have the rights listed below. To exercise your privacy rights, please click here.",
  "You may request confirmation of whether Company is collecting, sharing, or selling your consumer health data.",
  "You may request access and obtain a copy of the specific pieces of consumer health information we have collected about you, including a list of all third parties and affiliates with whom we have shared or sold the consumer health data and an active email address or other online mechanism that you may use to contact these third parties.",
  "You may request to withdraw consent from our collection (i.e. use) and sharing (with third parties and affiliates) of your consumer health data.",
  "You may request deletion of your consumer health data.",
  "You may request Company to reconsider a denial of a consumer health data request. If your appeal is unsuccessful, you can raise a complaint with the Washington State Attorney General at https://www.atg.wa.gov/file-complaint.",
  "In order to protect your consumer health data from unauthorized access or deletion, we may require you to verify your account credentials before you can submit a privacy rights request. If you do not have an account with us, or if we suspect that your account has been accessed without your authorization, we may ask you to provide additional Personal Data for verification.",
  "We are legally obligated to verify your identity when you submit a request. We may request additional information from you to verify your identity. If you submit a request to delete your Personal Data, you will also be required to confirm the deletion request by email.",
  "If we are subsequently unable to confirm your identity, we may refuse your privacy rights request.",
  "Only you may request related to your consumer health data, it does not allow any authorized individuals to make a request on your behalf.",
  "To exercise any of these rights, please click here.",
  "We may revise this Consumer Health Data Privacy Notice from time to time. If we make material changes to this Consumer Health Data Privacy Notice, we will notify you by email or by posting a notice on our Platform prior to or on the effective date of the changes. By continuing to access or use the Platform after those changes become effective, you acknowledge the revised Consumer Health Data Privacy Notice.",
];

export const trustArcLinks: { [key: string]: string } = {
  "https://familyfirstlifeusa.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=ec980c82-78b0-4499-bb9b-c74fde2d2288",
  "https://tidewatermg.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=fc2e34b4-de2d-42ed-a034-25bb0f9a22a7",
  "https://legacysafeguard.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=3d705d70-22a2-4dc7-93a0-9d5b7e50396b",
  "https://premiersmi.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=47bb6c72-c847-4e97-bf0b-b138ba6ed900",
  "https://naaleads.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=20c30679-7195-43cc-9b34-fcb078f48cb8",
  "https://copelandgroupusa.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=56d1dc2d-ad27-4dd5-a413-0130febe4853",
  "https://agent.familyfirstlife.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=f9e5f777-a067-4572-97c5-8fac6049d82f",
  "https://aimc.net/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=f5fa466f-935a-4658-8294-28a2788e1ff4",
  "https://cornerstoneseniormarketing.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=7cf4286a-2a64-4673-9fe0-1f581a86d827",
  "https://leads.integrity.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=96fdff44-3365-4c2a-96e1-93432d12fc2a",
  "https://www.thomasarts.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=a308c499-9fa4-49a5-8ad8-43b9dc78acdd",
  "https://palmettosb.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=e710677c-e431-4cd9-9656-3fb2416a6a01",
  "https://pennglobalmarketing.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=e72a2641-7665-4c6f-a62e-bae46289a8ac",
  "https://silversneakers.planenroll.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=93644e80-473e-43fe-aaa9-014d2700800a",
  "https://planenroll.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=4ee8bab4-f2b5-447e-8b2c-d41d18058fef",
  "https://integrity.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=81e0f329-8561-4493-b6f3-e59d89055c91",
  "https://westernassetprotection.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=a42588f5-79bf-44cf-b815-7c65b18e6e3d",
  "https://westernpenn.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=6d3868a2-403a-4de6-b05c-cbb46cfab1ca",
  "https://fidelisagents.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=165c7dd0-79ab-4249-a058-c620e17477ce",
  "https://aegisfinancial.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=fb567448-b3cd-40bb-bd1e-8ef276afc60a",
  "https://aep.tidewatermg.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=af31e850-bd25-467d-b125-b7703ac5d4d7",
  "https://vip.tidewatermg.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=a5b9d3e0-26b2-4bc9-9f4e-7215156c002b",
  "https://seniorinsurancespecialists.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=328304a1-a1de-4cbd-97b8-d20dd6685f2e",
  "https://emrickgroup.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=ce4bbfa5-de48-428a-8509-e489b1bc49d8",
  "https://americanseniorbenefits.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=2f24fc40-bab9-47d9-bd5b-aca58beb29eb",
  "https://beneficiarychoice.org/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=4be88fcd-5ddd-4669-bf48-fb9672f992bc",
  "https://fflnational.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=f7b717ba-fa95-4637-87be-025e74769468",
  "https://hgicrusade.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=c4151920-3752-4287-b9ce-a2750e2a71dc",
  "https://humanaachieve.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=4ca8c9ed-a628-4c53-8620-02c99533f004",
  "https://leazergroup.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=03ef567d-5cc6-4f3d-933b-6b9a077da7b3",
  "https://wapcon2024.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=13cc5f18-0392-462c-8105-fc955efe2e58",
  "https://lionstreet.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=ebf18504-6165-4a69-ba0a-10dd8ad93adc",
  "https://www.orgcorp.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=453c11ba-96c9-4783-a79c-f5a5d578b55b",
  "https://deftresearch.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=77c93d88-35a9-4588-aa91-b0eab6a5b88f",
  "https://appliedga.com/":
    "https://submit-irm.trustarc.com/services/validation/d14968e7-edec-4831-b5f2-c494567844f6/?brandId=c5f931f8-70cc-49ce-81d1-5f48b2b51f83",
};
